### ISSUE TITLE
http请求方式问题

### ISSUE THREAD

**Issue by sephyrothcloud** [PandaQAQ/RxPanda#3]
当使用http方式请求时，不会使用PandaResponseBodyConverter而是使用CastFunc<T>解析responseBody，此时会出现com.google.gson.internal.LinkedTreeMap cannot be cast to XXX错误，请问该如何进行修改。

**Comment by PandaQAQ** [comment]
> 当使用http方式请求时，不会使用PandaResponseBodyConverter而是使用CastFunc解析responseBody，此时会出现com.google.gson.internal.LinkedTreeMap cannot be cast to XXX错误，请问该如何进行修改。

http 方式是直接获取到响应的 Json 数据后使用 Gson 进行解析。与 Retrofit 方式中使用 @RealEntity 类似。回调中传入的解析类型需要写完整的数据结构，而不是 ApiData<T> 中的泛型。可以参考 sample -->MainActivity 中的 post 请求
