### ISSUE TITLE
token无感刷新

### ISSUE THREAD

**Issue by jpsz01** [PandaQAQ/RxPanda#4]
一般后台会设置token的过期时间跟失效时间，如果token失效了那自动跳转登陆页面，这个没有什么问题，但如果token过期了需要中断接口请求并用旧token请求接口更新当前token，更新完成了之后要继续请求被中断的接口，做到用户无感知，这个你有考虑加入现在这个框架吗，我自己是用retryWhen实现的，参考了这位博主的方法，如果你也有考虑添加这个功能的话希望对你有帮助，https://blog.csdn.net/jdsjlzx/article/details/52442113

**Comment by PandaQAQ** [comment]
> 一般后台会设置token的过期时间跟失效时间，如果token失效了那自动跳转登陆页面，这个没有什么问题，但如果token过期了需要中断接口请求并用旧token请求接口更新当前token，更新完成了之后要继续请求被中断的接口，做到用户无感知，这个你有考虑加入现在这个框架吗，我自己是用retryWhen实现的，参考了这位博主的方法，如果你也有考虑添加这个功能的话希望对你有帮助，https://blog.csdn.net/jdsjlzx/article/details/52442113

这个功能可以通过添加自定义的拦截器来实现，在拦截器中根据 token 过期错误码，去刷新token 并重置。刷新 token 这个操作包含了业务接口，放在框架中不太合适，不够灵活
